# Generated by Django 5.2.5 on 2025-09-02 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('sales', 'قسم المبيعات'), ('field_tech', 'فنيون ميدانيون'), ('customer_service', 'ملاحظات العملاء')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('branch', models.CharField(max_length=100, verbose_name='الفرع')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
