# Generated by Django 5.2.5 on 2025-09-02 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم التواصل')),
                ('issue_type', models.CharField(choices=[('complaint', 'شكوى'), ('suggestion', 'اقتراح'), ('appreciation', 'شكر')], max_length=15, verbose_name='نوع الملاحظة')),
                ('details', models.TextField(verbose_name='تفاصيل الملاحظة')),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('normal', 'عادي')], max_length=10, verbose_name='الأولوية')),
                ('follow_up_date', models.DateField(verbose_name='موعد المتابعة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق')], default='open', max_length=10, verbose_name='الحالة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sites_count', models.PositiveIntegerField(verbose_name='عدد المواقع')),
                ('maintenance_type', models.CharField(choices=[('inspection', 'فحص'), ('installation', 'تركيب'), ('repair', 'إصلاح')], max_length=15, verbose_name='نوع الصيانة')),
                ('condition_after', models.CharField(max_length=50, verbose_name='حالة النظام بعد الصيانة')),
                ('materials_used', models.TextField(blank=True, verbose_name='المواد المستهلكة')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='الموقع (GPS)')),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='field/before/', verbose_name='صورة قبل')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='field/after/', verbose_name='صورة بعد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clients_visited', models.PositiveIntegerField(verbose_name='عدد العملاء الذين تم زياراتهم')),
                ('proposals_sent', models.PositiveIntegerField(verbose_name='عدد العروض المقدمة')),
                ('deals_closed', models.PositiveIntegerField(verbose_name='عدد الصفقات المغلقة')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة العروض (ريال)')),
                ('interested_clients', models.TextField(blank=True, verbose_name='العملاء المهتمين')),
                ('next_appointments', models.TextField(blank=True, verbose_name='المواعيد القادمة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
